# -*- coding: utf-8 -*-
"""pdc-Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIF-YRyRpbQIzhDUBTYFciNXt8TsCqm2
"""

import multiprocessing
import time
import sys

def worker(rank, queue):
    try:
        # data chunk number is set to the process rank
        chunk = rank
        # sum of numbers from 1 to (rank * 10)
        numbers = list(range(1, rank * 10 + 1))
        result = sum(numbers)
        # message and computed result
        message = {
            'process_rank': rank,
            'task_chunk': chunk,
            'result': result
        }
        # Send the message to the master via the queue
        queue.put(message)
        print(f"Worker {rank} sent: {message}")
    except Exception as e:
        print(f"Worker {rank} encountered error: {e}", file=sys.stderr)
        queue.put({'error': str(e), 'rank': rank})

def master(num_workers, queue):
    # Start worker processes
    processes = []
    for i in range(1, num_workers + 1):
        p = multiprocessing.Process(target=worker, args=(i, queue))
        processes.append(p)
        p.start()

    # Optional: Add timeout to prevent hanging
    # Wait for all workers to finish (with timeout)
    for p in processes:
        p.join(timeout=10)  # 10 second timeout
        if p.is_alive():
            print(f"Process {p.pid} timed out, terminating...")
            p.terminate()
            p.join()

    # Collect and print messages from the queue
    collected_results = []
    while not queue.empty():
        try:
            message = queue.get_nowait()
            collected_results.append(message)
            print(f"Received: {message}")
        except:
            break

    return collected_results

if __name__ == "__main__":
    num_workers = 3
    queue = multiprocessing.Queue()
    results = master(num_workers, queue)
    print(f"\nTotal results collected: {len(results)}")

import multiprocessing
import time

def worker(rank, queue):
    # Simulate assigned task: data chunk number is set to the process rank
    chunk = rank
    # Simple computation: sum of numbers from 1 to (rank * 10)
    numbers = list(range(1, rank * 10 + 1))
    result = sum(numbers)
    #  message for process rank, assigned task (data chunk number), and computed result
    message = f"Process {rank}, Task {chunk}, Result {result}"
    #  message to the master via the queue
    queue.put(message)
    print(f"Worker {rank} sent: {message}")

def master(num_workers, queue):
    # Start worker processes
    processes = []
    for i in range(1, num_workers + 1):
        p = multiprocessing.Process(target=worker, args=(i, queue))
        processes.append(p)
        p.start()

    for p in processes:
        p.join()

    # Collect and print messages from the queue
    while not queue.empty():
        message = queue.get()
        print(f"Received: {message}")

if __name__ == "__main__":
    # Number of worker processes
    num_workers = 3
    #queue for message passing
    queue = multiprocessing.Queue()
    # master function
    master(num_workers, queue)